test: don't use `setEncoding()` in Transform tests
causes error on <= v0.8.x node:

  TypeError: Object [object Object] has no method 'end'
  at onread (/home/travis/build/TooTallNate/node-stream-parser/node_modules/readable-stream/lib/_stream_readable.js:242:29)

/cc @isaacs